/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/model/case.glb -o src/components/3d-Render/3d/case.js -k -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Case(props) {
  const { nodes, materials } = useGLTF('/model/case.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="main" geometry={nodes.main.geometry} material={nodes.main.material} position={[0.016, 0.281, 0.063]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
      <group name="ram" position={[0.016, 0, 0]}>
        <mesh name="mesh_1" geometry={nodes.mesh_1.geometry} material={nodes.mesh_1.material} />
        <mesh name="mesh_1_1" geometry={nodes.mesh_1_1.geometry} material={nodes.mesh_1_1.material} />
        <mesh name="mesh_1_2" geometry={nodes.mesh_1_2.geometry} material={nodes.mesh_1_2.material} />
      </group>
      <group name="ram_1" position={[0.016, 0, 0]}>
        <mesh name="mesh_2" geometry={nodes.mesh_2.geometry} material={nodes.mesh_2.material} />
        <mesh name="mesh_2_1" geometry={nodes.mesh_2_1.geometry} material={nodes.mesh_2_1.material} />
        <mesh name="mesh_2_2" geometry={nodes.mesh_2_2.geometry} material={nodes.mesh_2_2.material} />
      </group>
      <mesh name="ssd" geometry={nodes.ssd.geometry} material={nodes.ssd.material} position={[0.05, 0.219, 0.031]} rotation={[-Math.PI / 2, 0, 1.588]} />
      <mesh name="ssd_1" geometry={nodes.ssd_1.geometry} material={nodes.ssd_1.material} position={[0.113, 0.344, 0.031]} rotation={[3.072, -0.017, 1.57]} />
      <mesh name="psw" geometry={nodes.psw.geometry} material={nodes.psw.material} />
      <mesh name="psw_1" geometry={nodes.psw_1.geometry} material={nodes.psw_1.material} />
      <mesh name="cube" geometry={nodes.cube.geometry} material={nodes.cube.material} />
      <group name="cube_1" position={[0, 0.25, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh name="mesh_8" geometry={nodes.mesh_8.geometry} material={nodes.mesh_8.material} />
        <mesh name="mesh_8_1" geometry={nodes.mesh_8_1.geometry} material={nodes.mesh_8_1.material} />
        <mesh name="mesh_8_2" geometry={nodes.mesh_8_2.geometry} material={nodes.mesh_8_2.material} />
      </group>
      <group name="cube_2" rotation={[0, 0, -Math.PI / 2]}>
        <mesh name="mesh_9" geometry={nodes.mesh_9.geometry} material={nodes.mesh_9.material} />
        <mesh name="mesh_9_1" geometry={nodes.mesh_9_1.geometry} material={nodes.mesh_9_1.material} />
        <mesh name="mesh_9_2" geometry={nodes.mesh_9_2.geometry} material={nodes.mesh_9_2.material} />
      </group>
      <mesh name="cube_3" geometry={nodes.cube_3.geometry} material={nodes.cube_3.material} rotation={[0, 0, -Math.PI / 2]} />
      <mesh name="cube_4" geometry={nodes.cube_4.geometry} material={nodes.cube_4.material} />
      <mesh name="hdd_1" geometry={nodes.hdd_1.geometry} material={nodes.hdd_1.material} />
      <mesh name="cube_5" geometry={nodes.cube_5.geometry} material={nodes.cube_5.material} />
    </group>
  )
}

useGLTF.preload('/model/case.glb')
