/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/model/case.glb -o src/components/3d-Render/3d/case.js -k -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Case(props) {
  const { nodes, materials } = useGLTF('/model/case.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_model" position={[-0.172, -1.753, 0.449]} rotation={[-1.773, -0.101, 2.024]} scale={0.059}>
        <mesh name="Object_33" geometry={nodes.Object_33.geometry} material={materials['material_0.003']} />
        <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials['material_0.003']} />
        <mesh name="Object_35" geometry={nodes.Object_35.geometry} material={materials['material_0.003']} />
        <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials['material_0.003']} />
        <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials['material_6.002']} />
        <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials['material_7.002']} />
        <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials['material_0.003']} />
        <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials['material_8.002']} />
        <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials['material_9.002']} />
        <mesh name="Object_3" geometry={nodes.Object_3.geometry} material={materials['material_6.002']} />
        <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials['material_0.003']} />
        <mesh name="Object_29" geometry={nodes.Object_29.geometry} material={materials['material_1.002']} />
        <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials['material_1.002']} />
        <mesh name="Object_31" geometry={nodes.Object_31.geometry} material={materials['material_1.002']} />
        <mesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials['material_2.002']} />
        <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials['material_1.002']} />
        <mesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials['material_3.002']} />
        <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials['material_0.003']} />
        <mesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials['material_4.002']} />
        <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials['material_4.002']} />
        <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials['material_5.002']} />
        <mesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials['material_5.002']} />
        <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials['material_5.002']} />
        <mesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials['material_5.002']} />
        <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials['material_5.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/model/case.glb')
