/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/model/cpu.glb -o src/components/cpu.js -k -r public 
Author: Piekub.Nakub (https://sketchfab.com/Piekub.Nakub)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/intel-cpu-core-i7-11700k-3-748bc92c35dd40f5a94637ded887c972
Title: Intel CPU Core i7 11700K 3
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Cpu(props) {
  const { nodes, materials } = useGLTF('/model/cpu.glb')
  return (
    <group {...props} dispose={null}>
      <group name="cube_0" rotation={[0.129, -0.624, 0.076]}>
        <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.material_0} />
        <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.material_1} />
      </group>
      <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.material_2} />
      <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.material_3} />
    </group>
  )
}

useGLTF.preload('/model/cpu.glb')
