/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/model/cpu.glb -o src/components/3d-Render/3d/cpu.js -k -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Cpu(props) {
  const { nodes, materials } = useGLTF('/model/cpu.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_model001" position={[0.057, -1.341, 0.371]} rotation={[-1.673, -0.217, -2.14]} scale={4.175}>
        <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
          <group name="cube_0" rotation={[0.129, -0.624, 0.076]}>
            <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials['material_0.002']} position={[-0.087, 0.021, -0.073]} scale={0.701} />
            <mesh name="Object_7001" geometry={nodes.Object_7001.geometry} material={materials['material_1.001']} position={[-0.087, 0.021, -0.073]} scale={0.701} />
          </group>
          <mesh name="Object_10001" geometry={nodes.Object_10001.geometry} material={materials['material_3.001']} />
          <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials['material_2.001']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/model/cpu.glb')
