/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/model/gpu.glb -o src/components/3d-Render/3d/gpu.js -k -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Gpu(props) {
  const { nodes, materials } = useGLTF('/model/gpu.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_model" position={[0, 0.127, 0]} rotation={[-1.02, 0.521, 0.986]} scale={0.434}>
        <group name="DrakeIndustries_GPUfbx" rotation={[Math.PI / 2, 0, 0]}>
          <group name="Back" position={[7.034, 0, 0]} scale={[0.041, 1, 1]}>
            <group name="group5" position={[-285.114, 0, 0]} scale={[39.079, 1, 1]}>
              <mesh name="pCube143_darkGrey_0" geometry={nodes.pCube143_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, -0.086, 0.034]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube144_darkGrey_0" geometry={nodes.pCube144_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, -0.086, 0.233]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube145_darkGrey_0" geometry={nodes.pCube145_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, -0.086, 0.433]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube146_darkGrey_0" geometry={nodes.pCube146_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, -0.086, -0.173]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube147_darkGrey_0" geometry={nodes.pCube147_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, -0.086, -0.38]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube148_darkGrey_0" geometry={nodes.pCube148_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, -0.086, -0.587]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube149_darkGrey_0" geometry={nodes.pCube149_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, -0.086, -0.794]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube150_darkGrey_0" geometry={nodes.pCube150_darkGrey_0.geometry} material={materials.darkGrey} position={[7.495, -0.086, -1.001]} scale={[0.009, 0.123, 0.123]} />
              <mesh name="pCube151_darkGrey_0" geometry={nodes.pCube151_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, -0.086, -1.208]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube152_darkGrey_0" geometry={nodes.pCube152_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, -0.086, -1.415]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube153_darkGrey_0" geometry={nodes.pCube153_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, -0.086, -1.622]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube154_darkGrey_0" geometry={nodes.pCube154_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, -0.268, -1.415]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube155_darkGrey_0" geometry={nodes.pCube155_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, -0.268, -0.794]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube156_darkGrey_0" geometry={nodes.pCube156_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, -0.268, -1.001]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube157_darkGrey_0" geometry={nodes.pCube157_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, -0.268, -1.208]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube158_darkGrey_0" geometry={nodes.pCube158_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, -0.268, -0.587]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube159_darkGrey_0" geometry={nodes.pCube159_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, -0.268, -0.38]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube160_darkGrey_0" geometry={nodes.pCube160_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, -0.268, -0.173]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube161_darkGrey_0" geometry={nodes.pCube161_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, -0.268, 0.433]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube162_darkGrey_0" geometry={nodes.pCube162_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, -0.268, 0.233]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube163_darkGrey_0" geometry={nodes.pCube163_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, -0.268, 0.034]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube164_darkGrey_0" geometry={nodes.pCube164_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.114, -1.415]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube165_darkGrey_0" geometry={nodes.pCube165_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.114, -0.794]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube166_darkGrey_0" geometry={nodes.pCube166_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.114, -1.001]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube167_darkGrey_0" geometry={nodes.pCube167_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.114, -1.208]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube168_darkGrey_0" geometry={nodes.pCube168_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.114, -0.587]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube169_darkGrey_0" geometry={nodes.pCube169_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.114, -0.38]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube170_darkGrey_0" geometry={nodes.pCube170_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.114, -0.173]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube171_darkGrey_0" geometry={nodes.pCube171_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.114, 0.433]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube172_darkGrey_0" geometry={nodes.pCube172_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.114, 0.233]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube173_darkGrey_0" geometry={nodes.pCube173_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.114, 0.034]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube174_darkGrey_0" geometry={nodes.pCube174_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.114, 0.651]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube175_darkGrey_0" geometry={nodes.pCube175_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.281, 0.034]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube176_darkGrey_0" geometry={nodes.pCube176_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.281, 0.233]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube177_darkGrey_0" geometry={nodes.pCube177_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.281, 0.433]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube178_darkGrey_0" geometry={nodes.pCube178_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.281, -0.173]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube179_darkGrey_0" geometry={nodes.pCube179_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.281, -0.38]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube180_darkGrey_0" geometry={nodes.pCube180_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.281, -0.587]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube181_darkGrey_0" geometry={nodes.pCube181_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.281, -1.208]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube182_darkGrey_0" geometry={nodes.pCube182_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.281, -1.001]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube183_darkGrey_0" geometry={nodes.pCube183_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.281, -0.794]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube184_darkGrey_0" geometry={nodes.pCube184_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.281, 0.651]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube185_darkGrey_0" geometry={nodes.pCube185_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.114, 1.24]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube186_darkGrey_0" geometry={nodes.pCube186_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.114, 1.469]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube187_darkGrey_0" geometry={nodes.pCube187_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.114, 1.697]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube188_darkGrey_0" geometry={nodes.pCube188_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.114, 1.875]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube189_darkGrey_0" geometry={nodes.pCube189_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.114, 2.092]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube190_darkGrey_0" geometry={nodes.pCube190_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.114, 2.298]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube191_darkGrey_0" geometry={nodes.pCube191_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.114, 2.504]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube192_darkGrey_0" geometry={nodes.pCube192_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.114, 2.718]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube193_darkGrey_0" geometry={nodes.pCube193_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, -0.072, 2.298]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube194_darkGrey_0" geometry={nodes.pCube194_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, -0.072, 2.092]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube195_darkGrey_0" geometry={nodes.pCube195_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, -0.072, 1.875]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube196_darkGrey_0" geometry={nodes.pCube196_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, -0.258, 2.298]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube197_darkGrey_0" geometry={nodes.pCube197_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, -0.258, 2.092]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube198_darkGrey_0" geometry={nodes.pCube198_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, -0.258, 1.875]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube199_darkGrey_0" geometry={nodes.pCube199_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.294, 1.875]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube200_darkGrey_0" geometry={nodes.pCube200_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.294, 1.697]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube201_darkGrey_0" geometry={nodes.pCube201_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.294, 1.469]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube202_darkGrey_0" geometry={nodes.pCube202_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.294, 1.24]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube203_darkGrey_0" geometry={nodes.pCube203_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.475, 1.697]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube204_darkGrey_0" geometry={nodes.pCube204_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.475, 1.875]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube205_darkGrey_0" geometry={nodes.pCube205_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.655, 1.697]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube206_darkGrey_0" geometry={nodes.pCube206_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.655, 1.875]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube207_darkGrey_0" geometry={nodes.pCube207_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, -0.078, 1.263]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube208_darkGrey_0" geometry={nodes.pCube208_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, -0.27, 1.285]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube209_darkGrey_0" geometry={nodes.pCube209_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, -0.27, 1.082]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube210_darkGrey_0" geometry={nodes.pCube210_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, -0.078, 1.06]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube211_darkGrey_0" geometry={nodes.pCube211_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.467, -0.916]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube212_darkGrey_0" geometry={nodes.pCube212_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.636, -0.9]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube213_darkGrey_0" geometry={nodes.pCube213_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.114, -1.823]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube214_darkGrey_0" geometry={nodes.pCube214_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.281, -1.823]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube215_darkGrey_0" geometry={nodes.pCube215_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.114, -2.031]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube216_darkGrey_0" geometry={nodes.pCube216_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.281, -2.031]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube217_darkGrey_0" geometry={nodes.pCube217_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.461, 0.307]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube218_darkGrey_0" geometry={nodes.pCube218_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.642, 0.312]} scale={[0.014, 0.123, 0.123]} />
              <mesh name="pCube219_darkGrey_0" geometry={nodes.pCube219_darkGrey_0.geometry} material={materials.darkGrey} position={[7.493, 0.305, 2.718]} scale={[0.014, 0.123, 0.123]} />
            </group>
            <group name="Screws" position={[-174.856, 0, 0]} scale={[24.373, 1, 1]}>
              <mesh name="pSphere1_Metal_0" geometry={nodes.pSphere1_Metal_0.geometry} material={materials.Metal} position={[7.502, -0.165, 2.644]} rotation={[-0.326, 0.005, -0.011]} scale={[0.091, 0.143, 0.143]} />
              <mesh name="pSphere12_Metal_0" geometry={nodes.pSphere12_Metal_0.geometry} material={materials.Metal} position={[4.03, 0.449, -3.089]} rotation={[-2.078, -1.389, 1.079]} scale={[0.091, 0.112, 0.112]} />
              <mesh name="pSphere13_Metal_0" geometry={nodes.pSphere13_Metal_0.geometry} material={materials.Metal} position={[-3.639, 0.417, -3.097]} rotation={[1.65, -0.345, -1.586]} scale={[0.091, 0.084, 0.084]} />
              <mesh name="pSphere2_Metal_0" geometry={nodes.pSphere2_Metal_0.geometry} material={materials.Metal} position={[7.502, 0.331, 2.288]} rotation={[0.627, -0.006, -0.01]} scale={[0.091, 0.143, 0.143]} />
              <mesh name="pSphere3_Metal_0" geometry={nodes.pSphere3_Metal_0.geometry} material={materials.Metal} position={[7.502, -0.198, 1.627]} rotation={[-0.482, 0.006, -0.01]} scale={[0.091, 0.143, 0.143]} />
              <mesh name="pSphere4_Metal_0" geometry={nodes.pSphere4_Metal_0.geometry} material={materials.Metal} position={[7.502, 0.246, 1.004]} rotation={[-2.041, 0.01, 0.006]} scale={[0.091, 0.143, 0.143]} />
              <mesh name="pSphere5_Metal_0" geometry={nodes.pSphere5_Metal_0.geometry} material={materials.Metal} position={[7.49, -0.174, 0.76]} rotation={[-2.636, 0.035, -0.079]} scale={[0.091, 0.143, 0.143]} />
              <mesh name="pSphere6_Metal_0" geometry={nodes.pSphere6_Metal_0.geometry} material={materials.Metal} position={[7.49, -0.208, -1.865]} rotation={[2.966, 0.015, -0.011]} scale={[0.091, 0.143, 0.143]} />
              <mesh name="pSphere7_Metal_0" geometry={nodes.pSphere7_Metal_0.geometry} material={materials.Metal} position={[7.49, 0.222, -1.591]} rotation={[-2.902, 0.009, -0.016]} scale={[0.091, 0.143, 0.143]} />
            </group>
            <mesh name="pCube127_darkGrey_0" geometry={nodes.pCube127_darkGrey_0.geometry} material={materials.darkGrey} />
            <mesh name="pCube130_darkGrey_0" geometry={nodes.pCube130_darkGrey_0.geometry} material={materials.darkGrey} position={[3.224, 0, 0]} scale={[0.556, 1, 1]} />
            <mesh name="pCube133_Metal_0" geometry={nodes.pCube133_Metal_0.geometry} material={materials.Metal} position={[-0.303, 0, 0]} />
            <mesh name="pCube134_Metal_0" geometry={nodes.pCube134_Metal_0.geometry} material={materials.Metal} />
            <mesh name="pCube135_Metal_0" geometry={nodes.pCube135_Metal_0.geometry} material={materials.Metal} position={[-0.303, 0, 0]} />
            <mesh name="pCube136_Metal_0" geometry={nodes.pCube136_Metal_0.geometry} material={materials.Metal} position={[-0.303, 0, 0]} />
            <mesh name="pCube137_Metal_0" geometry={nodes.pCube137_Metal_0.geometry} material={materials.Metal} position={[-0.303, 0, 0]} />
            <mesh name="pCube220_darkGrey_0" geometry={nodes.pCube220_darkGrey_0.geometry} material={materials.darkGrey} />
          </group>
          <group name="group6" scale={[1, 0.839, 1]}>
            <mesh name="pCube223_Gold_0" geometry={nodes.pCube223_Gold_0.geometry} material={materials.Gold} position={[-7.015, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube224_Gold_0" geometry={nodes.pCube224_Gold_0.geometry} material={materials.Gold} position={[-6.898, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube225_Gold_0" geometry={nodes.pCube225_Gold_0.geometry} material={materials.Gold} position={[-6.789, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube226_Gold_0" geometry={nodes.pCube226_Gold_0.geometry} material={materials.Gold} position={[-6.668, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube227_Gold_0" geometry={nodes.pCube227_Gold_0.geometry} material={materials.Gold} position={[-6.523, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube228_Gold_0" geometry={nodes.pCube228_Gold_0.geometry} material={materials.Gold} position={[-6.392, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube229_Gold_0" geometry={nodes.pCube229_Gold_0.geometry} material={materials.Gold} position={[-6.253, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube230_Gold_0" geometry={nodes.pCube230_Gold_0.geometry} material={materials.Gold} position={[-6.253, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube231_Gold_0" geometry={nodes.pCube231_Gold_0.geometry} material={materials.Gold} position={[-6.112, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube232_Gold_0" geometry={nodes.pCube232_Gold_0.geometry} material={materials.Gold} position={[-5.995, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube233_Gold_0" geometry={nodes.pCube233_Gold_0.geometry} material={materials.Gold} position={[-5.886, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube234_Gold_0" geometry={nodes.pCube234_Gold_0.geometry} material={materials.Gold} position={[-5.765, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube235_Gold_0" geometry={nodes.pCube235_Gold_0.geometry} material={materials.Gold} position={[-5.62, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube236_Gold_0" geometry={nodes.pCube236_Gold_0.geometry} material={materials.Gold} position={[-5.489, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube237_Gold_0" geometry={nodes.pCube237_Gold_0.geometry} material={materials.Gold} position={[-5.35, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube238_Gold_0" geometry={nodes.pCube238_Gold_0.geometry} material={materials.Gold} position={[-4.214, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube239_Gold_0" geometry={nodes.pCube239_Gold_0.geometry} material={materials.Gold} position={[-4.106, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube240_Gold_0" geometry={nodes.pCube240_Gold_0.geometry} material={materials.Gold} position={[-3.985, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube241_Gold_0" geometry={nodes.pCube241_Gold_0.geometry} material={materials.Gold} position={[-3.839, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube242_Gold_0" geometry={nodes.pCube242_Gold_0.geometry} material={materials.Gold} position={[-3.708, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube243_Gold_0" geometry={nodes.pCube243_Gold_0.geometry} material={materials.Gold} position={[-3.569, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube244_Gold_0" geometry={nodes.pCube244_Gold_0.geometry} material={materials.Gold} position={[-4.331, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube245_Gold_0" geometry={nodes.pCube245_Gold_0.geometry} material={materials.Gold} position={[-4.472, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube246_Gold_0" geometry={nodes.pCube246_Gold_0.geometry} material={materials.Gold} position={[-4.472, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube247_Gold_0" geometry={nodes.pCube247_Gold_0.geometry} material={materials.Gold} position={[-4.611, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube248_Gold_0" geometry={nodes.pCube248_Gold_0.geometry} material={materials.Gold} position={[-4.742, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube249_Gold_0" geometry={nodes.pCube249_Gold_0.geometry} material={materials.Gold} position={[-4.888, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube250_Gold_0" geometry={nodes.pCube250_Gold_0.geometry} material={materials.Gold} position={[-5.009, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube251_Gold_0" geometry={nodes.pCube251_Gold_0.geometry} material={materials.Gold} position={[-5.234, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube252_Gold_0" geometry={nodes.pCube252_Gold_0.geometry} material={materials.Gold} position={[-5.117, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube253_Gold_0" geometry={nodes.pCube253_Gold_0.geometry} material={materials.Gold} position={[-0.572, 0.698, 2.32]} scale={[0.081, 0.996, 0.13]} />
            <mesh name="pCube254_Gold_0" geometry={nodes.pCube254_Gold_0.geometry} material={materials.Gold} position={[-0.451, 0.698, 2.32]} scale={[0.081, 0.996, 0.13]} />
            <mesh name="pCube258_Gold_0" geometry={nodes.pCube258_Gold_0.geometry} material={materials.Gold} position={[-0.797, 0.698, 2.32]} scale={[0.081, 0.996, 0.13]} />
            <mesh name="pCube259_Gold_0" geometry={nodes.pCube259_Gold_0.geometry} material={materials.Gold} position={[-0.939, 0.698, 2.32]} scale={[0.081, 0.996, 0.13]} />
            <mesh name="pCube260_Gold_0" geometry={nodes.pCube260_Gold_0.geometry} material={materials.Gold} position={[-0.939, 0.698, 2.32]} scale={[0.081, 0.996, 0.13]} />
            <mesh name="pCube261_Gold_0" geometry={nodes.pCube261_Gold_0.geometry} material={materials.Gold} position={[-1.077, 0.698, 2.32]} scale={[0.081, 0.996, 0.13]} />
            <mesh name="pCube262_Gold_0" geometry={nodes.pCube262_Gold_0.geometry} material={materials.Gold} position={[-1.208, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube263_Gold_0" geometry={nodes.pCube263_Gold_0.geometry} material={materials.Gold} position={[-1.354, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube264_Gold_0" geometry={nodes.pCube264_Gold_0.geometry} material={materials.Gold} position={[-1.475, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube265_Gold_0" geometry={nodes.pCube265_Gold_0.geometry} material={materials.Gold} position={[-1.7, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube266_Gold_0" geometry={nodes.pCube266_Gold_0.geometry} material={materials.Gold} position={[-1.584, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube267_Gold_0" geometry={nodes.pCube267_Gold_0.geometry} material={materials.Gold} position={[-0.681, 0.698, 2.32]} scale={[0.081, 0.996, 0.13]} />
            <mesh name="pCube268_Gold_0" geometry={nodes.pCube268_Gold_0.geometry} material={materials.Gold} position={[-1.816, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube269_Gold_0" geometry={nodes.pCube269_Gold_0.geometry} material={materials.Gold} position={[-1.955, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube270_Gold_0" geometry={nodes.pCube270_Gold_0.geometry} material={materials.Gold} position={[-2.086, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube271_Gold_0" geometry={nodes.pCube271_Gold_0.geometry} material={materials.Gold} position={[-2.232, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube272_Gold_0" geometry={nodes.pCube272_Gold_0.geometry} material={materials.Gold} position={[-2.353, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube273_Gold_0" geometry={nodes.pCube273_Gold_0.geometry} material={materials.Gold} position={[-2.461, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube274_Gold_0" geometry={nodes.pCube274_Gold_0.geometry} material={materials.Gold} position={[-2.578, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube275_Gold_0" geometry={nodes.pCube275_Gold_0.geometry} material={materials.Gold} position={[-2.719, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube276_Gold_0" geometry={nodes.pCube276_Gold_0.geometry} material={materials.Gold} position={[-2.719, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube277_Gold_0" geometry={nodes.pCube277_Gold_0.geometry} material={materials.Gold} position={[-2.858, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube278_Gold_0" geometry={nodes.pCube278_Gold_0.geometry} material={materials.Gold} position={[-2.989, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube279_Gold_0" geometry={nodes.pCube279_Gold_0.geometry} material={materials.Gold} position={[-3.135, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube280_Gold_0" geometry={nodes.pCube280_Gold_0.geometry} material={materials.Gold} position={[-3.256, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube281_Gold_0" geometry={nodes.pCube281_Gold_0.geometry} material={materials.Gold} position={[-3.481, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube282_Gold_0" geometry={nodes.pCube282_Gold_0.geometry} material={materials.Gold} position={[-3.364, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube283_Gold_0" geometry={nodes.pCube283_Gold_0.geometry} material={materials.Gold} position={[4.319, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube284_Gold_0" geometry={nodes.pCube284_Gold_0.geometry} material={materials.Gold} position={[4.202, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube285_Gold_0" geometry={nodes.pCube285_Gold_0.geometry} material={materials.Gold} position={[4.427, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube286_Gold_0" geometry={nodes.pCube286_Gold_0.geometry} material={materials.Gold} position={[4.548, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube287_Gold_0" geometry={nodes.pCube287_Gold_0.geometry} material={materials.Gold} position={[4.694, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube288_Gold_0" geometry={nodes.pCube288_Gold_0.geometry} material={materials.Gold} position={[4.825, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube289_Gold_0" geometry={nodes.pCube289_Gold_0.geometry} material={materials.Gold} position={[4.963, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube290_Gold_0" geometry={nodes.pCube290_Gold_0.geometry} material={materials.Gold} position={[4.963, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube291_Gold_0" geometry={nodes.pCube291_Gold_0.geometry} material={materials.Gold} position={[5.105, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube292_Gold_0" geometry={nodes.pCube292_Gold_0.geometry} material={materials.Gold} position={[5.221, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube293_Gold_0" geometry={nodes.pCube293_Gold_0.geometry} material={materials.Gold} position={[5.33, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube294_Gold_0" geometry={nodes.pCube294_Gold_0.geometry} material={materials.Gold} position={[5.451, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube295_Gold_0" geometry={nodes.pCube295_Gold_0.geometry} material={materials.Gold} position={[5.597, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube296_Gold_0" geometry={nodes.pCube296_Gold_0.geometry} material={materials.Gold} position={[5.728, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube297_Gold_0" geometry={nodes.pCube297_Gold_0.geometry} material={materials.Gold} position={[5.866, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube310_Gold_0" geometry={nodes.pCube310_Gold_0.geometry} material={materials.Gold} position={[2.565, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube311_Gold_0" geometry={nodes.pCube311_Gold_0.geometry} material={materials.Gold} position={[2.449, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube312_Gold_0" geometry={nodes.pCube312_Gold_0.geometry} material={materials.Gold} position={[2.674, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube313_Gold_0" geometry={nodes.pCube313_Gold_0.geometry} material={materials.Gold} position={[2.795, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube314_Gold_0" geometry={nodes.pCube314_Gold_0.geometry} material={materials.Gold} position={[2.941, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube315_Gold_0" geometry={nodes.pCube315_Gold_0.geometry} material={materials.Gold} position={[3.072, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube316_Gold_0" geometry={nodes.pCube316_Gold_0.geometry} material={materials.Gold} position={[3.21, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube317_Gold_0" geometry={nodes.pCube317_Gold_0.geometry} material={materials.Gold} position={[3.21, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube318_Gold_0" geometry={nodes.pCube318_Gold_0.geometry} material={materials.Gold} position={[3.352, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube319_Gold_0" geometry={nodes.pCube319_Gold_0.geometry} material={materials.Gold} position={[4.113, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube320_Gold_0" geometry={nodes.pCube320_Gold_0.geometry} material={materials.Gold} position={[3.975, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube321_Gold_0" geometry={nodes.pCube321_Gold_0.geometry} material={materials.Gold} position={[3.844, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube322_Gold_0" geometry={nodes.pCube322_Gold_0.geometry} material={materials.Gold} position={[3.698, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube323_Gold_0" geometry={nodes.pCube323_Gold_0.geometry} material={materials.Gold} position={[3.577, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube324_Gold_0" geometry={nodes.pCube324_Gold_0.geometry} material={materials.Gold} position={[3.468, 0.559, 2.32]} scale={[0.081, 1.993, 0.13]} />
            <mesh name="pCube325_Gold_0" geometry={nodes.pCube325_Gold_0.geometry} material={materials.Gold} position={[2.333, 0.698, 2.32]} scale={[0.081, 0.996, 0.13]} />
            <mesh name="pCube326_Gold_0" geometry={nodes.pCube326_Gold_0.geometry} material={materials.Gold} position={[2.194, 0.698, 2.32]} scale={[0.081, 0.996, 0.13]} />
            <mesh name="pCube327_Gold_0" geometry={nodes.pCube327_Gold_0.geometry} material={materials.Gold} position={[2.063, 0.698, 2.32]} scale={[0.081, 0.996, 0.13]} />
            <mesh name="pCube328_Gold_0" geometry={nodes.pCube328_Gold_0.geometry} material={materials.Gold} position={[1.917, 0.698, 2.32]} scale={[0.081, 0.996, 0.13]} />
            <mesh name="pCube329_Gold_0" geometry={nodes.pCube329_Gold_0.geometry} material={materials.Gold} position={[1.796, 0.698, 2.32]} scale={[0.081, 0.996, 0.13]} />
            <mesh name="pCube330_Gold_0" geometry={nodes.pCube330_Gold_0.geometry} material={materials.Gold} position={[1.688, 0.698, 2.32]} scale={[0.081, 0.996, 0.13]} />
            <mesh name="pCube331_Gold_0" geometry={nodes.pCube331_Gold_0.geometry} material={materials.Gold} position={[1.571, 0.698, 2.32]} scale={[0.081, 0.996, 0.13]} />
            <mesh name="pCube332_Gold_0" geometry={nodes.pCube332_Gold_0.geometry} material={materials.Gold} position={[1.43, 0.698, 2.32]} scale={[0.081, 0.996, 0.13]} />
            <mesh name="pCube333_Gold_0" geometry={nodes.pCube333_Gold_0.geometry} material={materials.Gold} position={[1.43, 0.698, 2.32]} scale={[0.081, 0.996, 0.13]} />
            <mesh name="pCube334_Gold_0" geometry={nodes.pCube334_Gold_0.geometry} material={materials.Gold} position={[1.291, 0.698, 2.32]} scale={[0.081, 0.996, 0.13]} />
            <mesh name="pCube335_Gold_0" geometry={nodes.pCube335_Gold_0.geometry} material={materials.Gold} position={[1.16, 0.698, 2.32]} scale={[0.081, 0.996, 0.13]} />
            <mesh name="pCube336_Gold_0" geometry={nodes.pCube336_Gold_0.geometry} material={materials.Gold} position={[1.014, 0.698, 2.32]} scale={[0.081, 0.996, 0.13]} />
            <mesh name="pCube337_Gold_0" geometry={nodes.pCube337_Gold_0.geometry} material={materials.Gold} position={[0.893, 0.698, 2.32]} scale={[0.081, 0.996, 0.13]} />
            <mesh name="pCube338_Gold_0" geometry={nodes.pCube338_Gold_0.geometry} material={materials.Gold} position={[0.668, 0.698, 2.32]} scale={[0.081, 0.996, 0.13]} />
            <mesh name="pCube339_Gold_0" geometry={nodes.pCube339_Gold_0.geometry} material={materials.Gold} position={[0.785, 0.698, 2.32]} scale={[0.081, 0.996, 0.13]} />
          </group>
          <group name="PCI_Ex" position={[0, -0.282, 0.157]}>
            <mesh name="pCube121_Gold_0" geometry={nodes.pCube121_Gold_0.geometry} material={materials.Gold} />
            <mesh name="pCube122_Gold_0" geometry={nodes.pCube122_Gold_0.geometry} material={materials.Gold} />
            <mesh name="pCube139_Metal_0" geometry={nodes.pCube139_Metal_0.geometry} material={materials.Metal} />
            <mesh name="pCube27_darkGrey_0" geometry={nodes.pCube27_darkGrey_0.geometry} material={materials.darkGrey} />
            <mesh name="pCube54_darkGrey_0" geometry={nodes.pCube54_darkGrey_0.geometry} material={materials.darkGrey} />
          </group>
          <group name="pCube222" position={[0, 0.493, 0]} scale={[14.335, 1.354, 4.9]}>
            <mesh name="pCube222_BlueGlow_0" geometry={nodes.pCube222_BlueGlow_0.geometry} material={materials.BlueGlow} />
            <mesh name="pCube222_darkGrey_0" geometry={nodes.pCube222_darkGrey_0.geometry} material={materials.darkGrey} />
            <mesh name="pCube222_Rainbow_0" geometry={nodes.pCube222_Rainbow_0.geometry} material={materials.Rainbow} />
          </group>
          <mesh name="pCube1_lambert1_0" geometry={nodes.pCube1_lambert1_0.geometry} material={materials.lambert1} />
          <mesh name="pCube11_MatteBlack_0" geometry={nodes.pCube11_MatteBlack_0.geometry} material={materials.MatteBlack} />
          <mesh name="pCube20_MatteBlack_0" geometry={nodes.pCube20_MatteBlack_0.geometry} material={materials.MatteBlack} />
          <mesh name="pCube20_Rainbow_0" geometry={nodes.pCube20_Rainbow_0.geometry} material={materials.Rainbow} />
          <group name="fanBlades" position={[0, 0.658, 0]} scale={[1, 0.355, 1]}>
            <group name="fanBlades001" position={[0, 0.454, 0]} scale={[0.867, 0.814, 0.867]}>
              <mesh name="pCube10_MatteBlack_0002" geometry={nodes.pCube10_MatteBlack_0002.geometry} material={materials.MatteBlack} />
              <mesh name="pCube2_MatteBlack_0002" geometry={nodes.pCube2_MatteBlack_0002.geometry} material={materials.MatteBlack} />
              <mesh name="pCube3_MatteBlack_0002" geometry={nodes.pCube3_MatteBlack_0002.geometry} material={materials.MatteBlack} />
              <mesh name="pCube4_MatteBlack_0002" geometry={nodes.pCube4_MatteBlack_0002.geometry} material={materials.MatteBlack} />
              <mesh name="pCube5_MatteBlack_0002" geometry={nodes.pCube5_MatteBlack_0002.geometry} material={materials.MatteBlack} />
              <mesh name="pCube6_MatteBlack_0002" geometry={nodes.pCube6_MatteBlack_0002.geometry} material={materials.MatteBlack} />
              <mesh name="pCube7_MatteBlack_0002" geometry={nodes.pCube7_MatteBlack_0002.geometry} material={materials.MatteBlack} />
              <mesh name="pCube8_MatteBlack_0002" geometry={nodes.pCube8_MatteBlack_0002.geometry} material={materials.MatteBlack} />
              <mesh name="pCube9_MatteBlack_0002" geometry={nodes.pCube9_MatteBlack_0002.geometry} material={materials.MatteBlack} />
            </group>
            <group name="fanBlades1" position={[-4.366, 0.454, 0]} scale={[0.867, 0.814, 0.867]}>
              <mesh name="pCube10_MatteBlack_0001" geometry={nodes.pCube10_MatteBlack_0001.geometry} material={materials.MatteBlack} />
              <mesh name="pCube2_MatteBlack_0001" geometry={nodes.pCube2_MatteBlack_0001.geometry} material={materials.MatteBlack} />
              <mesh name="pCube3_MatteBlack_0001" geometry={nodes.pCube3_MatteBlack_0001.geometry} material={materials.MatteBlack} />
              <mesh name="pCube4_MatteBlack_0001" geometry={nodes.pCube4_MatteBlack_0001.geometry} material={materials.MatteBlack} />
              <mesh name="pCube5_MatteBlack_0001" geometry={nodes.pCube5_MatteBlack_0001.geometry} material={materials.MatteBlack} />
              <mesh name="pCube6_MatteBlack_0001" geometry={nodes.pCube6_MatteBlack_0001.geometry} material={materials.MatteBlack} />
              <mesh name="pCube7_MatteBlack_0001" geometry={nodes.pCube7_MatteBlack_0001.geometry} material={materials.MatteBlack} />
              <mesh name="pCube8_MatteBlack_0001" geometry={nodes.pCube8_MatteBlack_0001.geometry} material={materials.MatteBlack} />
              <mesh name="pCube9_MatteBlack_0001" geometry={nodes.pCube9_MatteBlack_0001.geometry} material={materials.MatteBlack} />
            </group>
            <group name="fanBlades2" position={[4.411, 0.454, -0.129]} rotation={[0, -0.21, 0]} scale={[0.867, 0.814, 0.867]}>
              <mesh name="pCube10_MatteBlack_0" geometry={nodes.pCube10_MatteBlack_0.geometry} material={materials.MatteBlack} />
              <mesh name="pCube2_MatteBlack_0" geometry={nodes.pCube2_MatteBlack_0.geometry} material={materials.MatteBlack} />
              <mesh name="pCube3_MatteBlack_0" geometry={nodes.pCube3_MatteBlack_0.geometry} material={materials.MatteBlack} />
              <mesh name="pCube4_MatteBlack_0" geometry={nodes.pCube4_MatteBlack_0.geometry} material={materials.MatteBlack} />
              <mesh name="pCube5_MatteBlack_0" geometry={nodes.pCube5_MatteBlack_0.geometry} material={materials.MatteBlack} />
              <mesh name="pCube6_MatteBlack_0" geometry={nodes.pCube6_MatteBlack_0.geometry} material={materials.MatteBlack} />
              <mesh name="pCube7_MatteBlack_0" geometry={nodes.pCube7_MatteBlack_0.geometry} material={materials.MatteBlack} />
              <mesh name="pCube8_MatteBlack_0" geometry={nodes.pCube8_MatteBlack_0.geometry} material={materials.MatteBlack} />
              <mesh name="pCube9_MatteBlack_0" geometry={nodes.pCube9_MatteBlack_0.geometry} material={materials.MatteBlack} />
            </group>
          </group>
          <mesh name="FanOuterRGB_Rainbow_0" geometry={nodes.FanOuterRGB_Rainbow_0.geometry} material={materials.Rainbow} />
          <mesh name="FanRGB_Rainbow_0" geometry={nodes.FanRGB_Rainbow_0.geometry} material={materials.Rainbow} />
          <group name="pCube340" position={[0, 0.699, -2.921]} scale={[12.977, 1.11, 0.63]}>
            <mesh name="pCube340_darkGrey_0" geometry={nodes.pCube340_darkGrey_0.geometry} material={materials.darkGrey} />
            <mesh name="pCube340_Metal_0" geometry={nodes.pCube340_Metal_0.geometry} material={materials.Metal} />
          </group>
          <mesh name="fanLogo_DrakeLogo_0" geometry={nodes.fanLogo_DrakeLogo_0.geometry} material={materials.DrakeLogo} />
          <mesh name="group9_MatteBlack_0" geometry={nodes.group9_MatteBlack_0.geometry} material={materials.MatteBlack} />
          <mesh name="pCube341_DrakeLogo_0" geometry={nodes.pCube341_DrakeLogo_0.geometry} material={materials.DrakeLogo} position={[0, 0.072, -2.648]} scale={[7.723, 1.022, 1]} />
          <group name="pCube347" position={[0.144, -0.028, 0]}>
            <mesh name="pCube347_MatteBlack_0" geometry={nodes.pCube347_MatteBlack_0.geometry} material={materials.MatteBlack} />
            <mesh name="pCube347_Metal_0" geometry={nodes.pCube347_Metal_0.geometry} material={materials.Metal} />
          </group>
          <mesh name="pCube351_MatteBlack_0" geometry={nodes.pCube351_MatteBlack_0.geometry} material={materials.MatteBlack} />
          <mesh name="pCube221_MatteBlack_0" geometry={nodes.pCube221_MatteBlack_0.geometry} material={materials.MatteBlack} position={[-7.05, -0.508, -0.39]} scale={[0.476, 0.523, 3.311]} />
          <mesh name="screws_Metal_0" geometry={nodes.screws_Metal_0.geometry} material={materials.Metal} position={[-0.069, 0, 0]} />
          <mesh name="pCube138_Rainbow_0" geometry={nodes.pCube138_Rainbow_0.geometry} material={materials.Rainbow} />
          <mesh name="pCube23_Metal_0" geometry={nodes.pCube23_Metal_0.geometry} material={materials.Metal} />
          <mesh name="pCube23_Rainbow_0" geometry={nodes.pCube23_Rainbow_0.geometry} material={materials.Rainbow} />
          <mesh name="pCube24_Metal_0" geometry={nodes.pCube24_Metal_0.geometry} material={materials.Metal} />
          <mesh name="pCube24_Rainbow_0" geometry={nodes.pCube24_Rainbow_0.geometry} material={materials.Rainbow} />
          <mesh name="pCube13_darkGrey_0" geometry={nodes.pCube13_darkGrey_0.geometry} material={materials.darkGrey} />
          <mesh name="pCube14_darkGrey_0" geometry={nodes.pCube14_darkGrey_0.geometry} material={materials.darkGrey} />
          <mesh name="pCube16_darkGrey_0" geometry={nodes.pCube16_darkGrey_0.geometry} material={materials.darkGrey} />
          <mesh name="pCube17_darkGrey_0" geometry={nodes.pCube17_darkGrey_0.geometry} material={materials.darkGrey} />
          <mesh name="pCube18_darkGrey_0" geometry={nodes.pCube18_darkGrey_0.geometry} material={materials.darkGrey} />
          <mesh name="pCube19_darkGrey_0" geometry={nodes.pCube19_darkGrey_0.geometry} material={materials.darkGrey} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/model/gpu.glb')
