/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/model/gpu.glb -o src/components/3d-Render/3d/gpu.js -k -r public 
Author: Astrien (https://sketchfab.com/Astrien)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/nvidia-geforce-rtx-3090-graphics-card-15d93e47af1c484e81cb5dd83cbbc121
Title: NVIDIA GeForce RTX 3090 Graphics Card
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Gpu(props) {
  const { nodes, materials } = useGLTF('/model/gpu.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
        <mesh name="Object_2" geometry={nodes.Object_2.geometry} material={materials['Material.002']} />
        <mesh name="Object_3" geometry={nodes.Object_3.geometry} material={materials['Material.003']} />
        <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials['Material.004']} />
        <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials['Material.005']} />
        <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.None} />
        <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials['black_glossy.003']} />
        <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.black_with_text} />
        <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.black_with_text} />
        <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.Metal} />
        <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.Metal} />
        <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.Metal} />
        <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.black_glossy} />
        <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials['black_glossy.001']} />
        <mesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials['black_glossy.001']} />
        <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials['black_glossy.002']} />
        <mesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.material} />
        <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.material} />
        <mesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials.material} />
        <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.material} />
        <mesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.material} />
        <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.material} />
        <mesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials.port} />
        <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.port_frame} />
      </group>
    </group>
  )
}

useGLTF.preload('/model/gpu.glb')
