/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/model/jcp.glb -o src/components/jcp.js -k -r public 
Author: Piekub.Nakub (https://sketchfab.com/Piekub.Nakub)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/jcp-ccb36b8826674aa9960f5f7f9a2eff4e
Title: JCP
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Jcp(props) {
  const { nodes, materials } = useGLTF('/model/jcp.glb')
  return (
    <group {...props} dispose={null}>
      <group name="J_8" position={[0.402, 0.224, -0.038]}>
        <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.material_0} position={[-0.627, 0.194, 0.025]} />
        <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.material_0} position={[-0.321, 0.415, -0.013]} rotation={[0, 0, 0.75]} />
        <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.material_0} position={[-0.321, 0.415, -0.013]} rotation={[0, 0, Math.PI / 2]} />
        <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.material_0} position={[-0.212, 0.451, -0.013]} rotation={[0, 0, -Math.PI / 4]} />
        <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.material_0} position={[-0.324, 0.335, 0.019]} rotation={[-Math.PI, 0, 2.339]} />
        <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.material_0} position={[-0.324, 0.335, 0.019]} rotation={[Math.PI, 0, -1.588]} />
        <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.material_0} position={[-0.324, 0.335, 0.019]} rotation={[Math.PI, 0, -2.409]} />
        <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.material_0} position={[-0.324, 0.335, 0.019]} rotation={[Math.PI, 0, 3.124]} />
      </group>
      <group name="C_23" position={[0.169, 0.109, -0.044]} rotation={[0, 0, 0.087]}>
        <mesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials.material_1} position={[0.029, -0.02, 0]} rotation={[0, 0, -2.374]} />
        <mesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials.material_1} position={[0.029, -0.02, 0]} rotation={[0, 0, 3.089]} />
        <mesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials.material_1} position={[0.052, -0.077, 0]} rotation={[0, 0, 2.321]} />
        <mesh name="Object_29" geometry={nodes.Object_29.geometry} material={materials.material_1} position={[0.003, 0.14, 0]} rotation={[0, 0, -1.641]} />
        <mesh name="Object_31" geometry={nodes.Object_31.geometry} material={materials.material_1} position={[0.016, 0.147, 0]} rotation={[0, 0, -1.152]} />
        <mesh name="Object_33" geometry={nodes.Object_33.geometry} material={materials.material_1} position={[0.042, 0.136, 0]} rotation={[0, 0, -1.641]} />
        <mesh name="Object_35" geometry={nodes.Object_35.geometry} material={materials.material_1} position={[-0.074, -0.078, 0]} rotation={[0, 0, -2.129]} />
        <mesh name="Object_37" geometry={nodes.Object_37.geometry} material={materials.material_1} position={[-0.052, 0.456, 0.25]} rotation={[-Math.PI, 0, 1.169]} />
        <mesh name="Object_39" geometry={nodes.Object_39.geometry} material={materials.material_1} position={[-0.052, 0.456, 0.25]} rotation={[-Math.PI, 0, 1.658]} />
        <mesh name="Object_41" geometry={nodes.Object_41.geometry} material={materials.material_1} position={[-0.052, 0.456, 0.25]} rotation={[-Math.PI, 0, 2.147]} />
        <mesh name="Object_43" geometry={nodes.Object_43.geometry} material={materials.material_1} position={[-0.052, 0.456, 0.25]} rotation={[-Math.PI, 0, 1.658]} />
        <mesh name="Object_45" geometry={nodes.Object_45.geometry} material={materials.material_1} position={[-0.052, 0.456, 0.25]} rotation={[Math.PI, 0, -0.663]} />
        <mesh name="Object_47" geometry={nodes.Object_47.geometry} material={materials.material_1} position={[-0.052, 0.456, 0.25]} rotation={[-Math.PI, 0, 0.105]} />
        <mesh name="Object_49" geometry={nodes.Object_49.geometry} material={materials.material_1} position={[-0.052, 0.456, 0.25]} rotation={[-Math.PI, 0, 0.925]} />
      </group>
      <group name="P_36" position={[0.142, 0.423, 0.072]} rotation={[0, 0, -0.017]}>
        <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials.material_0} position={[0.067, -0.835, -0.072]} />
        <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials.material_0} position={[0.086, -0.429, -0.116]} rotation={[0, 0, -Math.PI / 2]} />
        <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials.material_0} position={[0.086, -0.429, -0.116]} rotation={[0, 0, -Math.PI / 2]} />
        <mesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials.material_0} position={[0.178, -0.447, -0.116]} rotation={[0, 0, 0.367]} />
        <mesh name="Object_60" geometry={nodes.Object_60.geometry} material={materials.material_0} position={[0.178, -0.447, -0.116]} rotation={[0, 0, -0.244]} />
        <mesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials.material_0} position={[0.239, -0.374, -0.116]} rotation={[0, 0, 0.593]} />
        <mesh name="Object_64" geometry={nodes.Object_64.geometry} material={materials.material_0} position={[-0.067, 0.135, 0.134]} rotation={[Math.PI, 0, -2.601]} />
        <mesh name="Object_66" geometry={nodes.Object_66.geometry} material={materials.material_0} position={[-0.067, 0.135, 0.134]} rotation={[-Math.PI, 0, 2.845]} />
        <mesh name="Object_68" geometry={nodes.Object_68.geometry} material={materials.material_0} position={[-0.067, 0.135, 0.134]} rotation={[-Math.PI, 0, -2.827]} />
        <mesh name="Object_70" geometry={nodes.Object_70.geometry} material={materials.material_0} position={[-0.067, 0.135, 0.134]} rotation={[-Math.PI, 0, 1.518]} />
        <mesh name="Object_72" geometry={nodes.Object_72.geometry} material={materials.material_0} position={[-0.067, 0.135, 0.134]} rotation={[-Math.PI, 0, 1.518]} />
        <mesh name="Object_74" geometry={nodes.Object_74.geometry} material={materials.material_0} position={[-0.067, 0.135, 0.134]} rotation={[-Math.PI, 0, 3.089]} />
      </group>
      <group name="crop_49" position={[-0.236, 0.404, 0]}>
        <mesh name="Object_77" geometry={nodes.Object_77.geometry} material={materials.material_0} position={[0.589, 0.467, -0.044]} rotation={[0, 0, 0.576]} />
        <mesh name="Object_79" geometry={nodes.Object_79.geometry} material={materials.material_0} />
        <mesh name="Object_81" geometry={nodes.Object_81.geometry} material={materials.material_0} position={[0.613, -0.155, -0.044]} rotation={[0, 0, -0.576]} />
        <mesh name="Object_83" geometry={nodes.Object_83.geometry} material={materials.material_0} position={[0.653, 0.492, -0.044]} rotation={[0, 0, 1.169]} />
        <mesh name="Object_85" geometry={nodes.Object_85.geometry} material={materials.material_0} position={[0.29, -0.37, -0.044]} rotation={[0, 0, -1.169]} />
        <mesh name="Object_87" geometry={nodes.Object_87.geometry} material={materials.material_0} position={[0.409, 0.599, -0.044]} rotation={[0, 0, Math.PI / 2]} />
        <mesh name="Object_89" geometry={nodes.Object_89.geometry} material={materials.material_0} position={[0.528, 0.595, -0.044]} rotation={[0, 0, Math.PI / 2]} />
        <mesh name="Object_91" geometry={nodes.Object_91.geometry} material={materials.material_0} position={[0.413, 0.696, -0.044]} rotation={[0, 0, 2.094]} />
        <mesh name="Object_93" geometry={nodes.Object_93.geometry} material={materials.material_0} position={[0.007, -0.187, -0.044]} rotation={[0, 0, -2.094]} />
        <mesh name="Object_95" geometry={nodes.Object_95.geometry} material={materials.material_0} position={[0.024, 0.155, -0.044]} rotation={[Math.PI, 0, 2.566]} />
        <mesh name="Object_97" geometry={nodes.Object_97.geometry} material={materials.material_0} position={[0.024, 0.12, -0.044]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh name="Object_99" geometry={nodes.Object_99.geometry} material={materials.material_0} position={[0.024, 0.12, -0.044]} rotation={[-Math.PI, 0, -2.566]} />
      </group>
      <group name="back_70" position={[-0.225, 0.419, -0.013]}>
        <mesh name="Object_102" geometry={nodes.Object_102.geometry} material={materials.material_2} />
        <mesh name="Object_104" geometry={nodes.Object_104.geometry} material={materials.material_2} />
        <mesh name="Object_106" geometry={nodes.Object_106.geometry} material={materials.material_2} />
        <mesh name="Object_108" geometry={nodes.Object_108.geometry} material={materials.material_2} />
        <mesh name="Object_110" geometry={nodes.Object_110.geometry} material={materials.material_2} />
        <mesh name="Object_112" geometry={nodes.Object_112.geometry} material={materials.material_2} position={[0.103, -0.206, -0.028]} rotation={[0, 0, Math.PI / 2]} />
        <mesh name="Object_114" geometry={nodes.Object_114.geometry} material={materials.material_2} />
        <mesh name="Object_116" geometry={nodes.Object_116.geometry} material={materials.material_2} position={[0.541, -0.206, -0.028]} rotation={[0, 0, Math.PI / 2]} />
        <mesh name="Object_118" geometry={nodes.Object_118.geometry} material={materials.material_2} position={[0.438, 0, 0]} />
        <mesh name="Object_120" geometry={nodes.Object_120.geometry} material={materials.material_2} />
        <mesh name="Object_122" geometry={nodes.Object_122.geometry} material={materials.material_2} />
        <mesh name="Object_124" geometry={nodes.Object_124.geometry} material={materials.material_2} />
        <mesh name="Object_126" geometry={nodes.Object_126.geometry} material={materials.material_2} position={[0.555, 0.375, -0.028]} rotation={[0, 0, Math.PI / 2]} />
        <mesh name="Object_128" geometry={nodes.Object_128.geometry} material={materials.material_2} position={[0.555, 0.375, -0.028]} rotation={[0, 0, Math.PI / 2]} />
        <mesh name="Object_130" geometry={nodes.Object_130.geometry} material={materials.material_2} position={[0.555, 0.375, -0.028]} rotation={[0, 0, Math.PI / 2]} />
        <mesh name="Object_132" geometry={nodes.Object_132.geometry} material={materials.material_2} position={[0.555, 0.375, -0.028]} rotation={[0, 0, Math.PI / 2]} />
        <mesh name="Object_134" geometry={nodes.Object_134.geometry} material={materials.material_2} position={[0.555, 0.375, -0.028]} rotation={[0, 0, Math.PI / 2]} />
        <mesh name="Object_136" geometry={nodes.Object_136.geometry} material={materials.material_2} position={[0.555, 0.375, -0.028]} rotation={[0, 0, Math.PI / 2]} />
        <mesh name="Object_138" geometry={nodes.Object_138.geometry} material={materials.material_2} position={[0.555, 0.375, -0.028]} rotation={[0, 0, Math.PI / 2]} />
        <mesh name="Object_140" geometry={nodes.Object_140.geometry} material={materials.material_2} position={[0.555, 0.375, -0.028]} rotation={[0, 0, Math.PI / 2]} />
      </group>
    </group>
  )
}

useGLTF.preload('/model/jcp.glb')
