/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/model/mainboard.glb -o src/components/3d-Render/3d/mainboard.js -k -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function MainBoard(props) {
  const { nodes, materials } = useGLTF('/model/mainboard.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Node_455" position={[-0.568, 0.336, -0.856]} rotation={[0, -0.824, -1.488]} scale={4.705}>
        <group name="bone4" position={[-0.287, 0.062, -0.35]}>
          <mesh name="circle002" geometry={nodes.circle002.geometry} material={materials.Material_0} position={[0.075, 0.025, 0.13]} />
          <mesh name="circle003" geometry={nodes.circle003.geometry} material={materials.Material_0} position={[-0.07, 0.025, -0.066]} />
          <mesh name="cuboid398" geometry={nodes.cuboid398.geometry} material={materials.Material_5} />
        </group>
        <group name="juk" position={[-0.231, 0.062, 0.05]}>
          <mesh name="cylinder" geometry={nodes.cylinder.geometry} material={materials.Material_0} />
          <mesh name="cylinder001" geometry={nodes.cylinder001.geometry} material={materials.Material_0} position={[0, 0, 0.375]} />
          <mesh name="cylinder002" geometry={nodes.cylinder002.geometry} material={materials.Material_0} position={[0.4, 0, 0]} />
          <mesh name="cylinder003" geometry={nodes.cylinder003.geometry} material={materials.Material_0} position={[0.4, 0, 0.369]} />
          <mesh name="cylinder004" geometry={nodes.cylinder004.geometry} material={materials.Material_0} position={[0.331, 0, 0.384]} />
          <mesh name="cylinder005" geometry={nodes.cylinder005.geometry} material={materials.Material_0} position={[0.294, 0, 0.384]} />
          <mesh name="cylinder006" geometry={nodes.cylinder006.geometry} material={materials.Material_0} position={[0.261, 0, 0.384]} />
          <mesh name="cylinder007" geometry={nodes.cylinder007.geometry} material={materials.Material_0} position={[0.227, 0, 0.384]} />
          <mesh name="cylinder008" geometry={nodes.cylinder008.geometry} material={materials.Material_0} position={[0.187, 0, 0.384]} />
          <mesh name="cylinder009" geometry={nodes.cylinder009.geometry} material={materials.Material_0} position={[0.387, 0, 0.287]} />
          <mesh name="cylinder010" geometry={nodes.cylinder010.geometry} material={materials.Material_0} position={[0.425, 0, 0.288]} />
          <mesh name="cylinder011" geometry={nodes.cylinder011.geometry} material={materials.Material_0} position={[0.423, 0, 0.241]} />
          <mesh name="cylinder012" geometry={nodes.cylinder012.geometry} material={materials.Material_0} position={[0.661, 0, 0.208]} />
          <mesh name="cylinder013" geometry={nodes.cylinder013.geometry} material={materials.Material_0} position={[0.423, 0, 0.195]} />
          <mesh name="cylinder014" geometry={nodes.cylinder014.geometry} material={materials.Material_0} position={[0.386, 0, 0.195]} />
          <mesh name="cylinder015" geometry={nodes.cylinder015.geometry} material={materials.Material_0} position={[0.423, 0, 0.15]} />
          <mesh name="cylinder016" geometry={nodes.cylinder016.geometry} material={materials.Material_0} position={[0.423, 0, 0.106]} />
          <mesh name="cylinder017" geometry={nodes.cylinder017.geometry} material={materials.Material_0} position={[0.423, 0, 0.063]} />
          <mesh name="cylinder018" geometry={nodes.cylinder018.geometry} material={materials.Material_0} position={[0.386, 0, 0.106]} />
          <mesh name="cylinder019" geometry={nodes.cylinder019.geometry} material={materials.Material_0} position={[0.563, 0, -0.1]} />
          <mesh name="cylinder020" geometry={nodes.cylinder020.geometry} material={materials.Material_0} position={[0.458, 0, -0.1]} />
          <mesh name="cylinder021" geometry={nodes.cylinder021.geometry} material={materials.Material_0} position={[0.367, 0, -0.1]} />
          <mesh name="cylinder022" geometry={nodes.cylinder022.geometry} material={materials.Material_0} position={[0.525, 0, -0.244]} />
          <mesh name="cylinder023" geometry={nodes.cylinder023.geometry} material={materials.Material_0} position={[-0.158, 0, 0.431]} />
          <mesh name="cylinder024" geometry={nodes.cylinder024.geometry} material={materials.Material_0} position={[-0.158, 0, 0.231]} />
          <mesh name="cylinder025" geometry={nodes.cylinder025.geometry} material={materials.Material_0} position={[-0.183, 0, -0.225]} />
          <mesh name="cylinder026" geometry={nodes.cylinder026.geometry} material={materials.Material_0} position={[-0.178, 0, -0.322]} />
          <mesh name="cylinder027" geometry={nodes.cylinder027.geometry} material={materials.Material_0} position={[-0.178, 0, -0.356]} />
          <mesh name="cylinder028" geometry={nodes.cylinder028.geometry} material={materials.Material_0} position={[0.256, -0.003, 0.552]} />
          <mesh name="cylinder029" geometry={nodes.cylinder029.geometry} material={materials.Material_0} position={[0.413, -0.003, 0.552]} />
          <mesh name="cylinder030" geometry={nodes.cylinder030.geometry} material={materials.Material_0} position={[0.619, -0.003, 0.395]} />
          <mesh name="cylinder031" geometry={nodes.cylinder031.geometry} material={materials.Material_0} position={[0.619, -0.003, 0.245]} />
          <mesh name="cylinder032" geometry={nodes.cylinder032.geometry} material={materials.Material_0} position={[0.619, -0.003, 0.102]} />
          <mesh name="cylinder033" geometry={nodes.cylinder033.geometry} material={materials.Material_0} position={[0.57, -0.003, -0.247]} />
          <mesh name="cylinder034" geometry={nodes.cylinder034.geometry} material={materials.Material_0} position={[0.308, 0, -0.519]} />
          <mesh name="cylinder035" geometry={nodes.cylinder035.geometry} material={materials.Material_1} position={[-0.127, 0, -0.464]} />
          <mesh name="cylinder036" geometry={nodes.cylinder036.geometry} material={materials.Material_1} position={[0.019, 0, -0.27]} />
        </group>
        <group name="ramsouket" position={[-0.3, 0.025, 0.575]}>
          <group name="ramsouket2" position={[-0.05, 0, 0]}>
            <mesh name="cuboid007" geometry={nodes.cuboid007.geometry} material={materials.Material_4} position={[0.3, -0.025, -0.338]} />
            <mesh name="cuboid008" geometry={nodes.cuboid008.geometry} material={materials.Material_4} position={[0, 0, -0.669]} />
            <mesh name="cuboid009" geometry={nodes.cuboid009.geometry} material={materials.Material_4} rotation={[-Math.PI, 0, -Math.PI]} />
          </group>
          <mesh name="cuboid002" geometry={nodes.cuboid002.geometry} material={materials.Material_4} position={[0.3, -0.025, -0.338]} />
          <mesh name="cuboid003" geometry={nodes.cuboid003.geometry} material={materials.Material_4} position={[0, 0, -0.669]} />
          <mesh name="cuboid004" geometry={nodes.cuboid004.geometry} material={materials.Material_4} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh name="cuboid005" geometry={nodes.cuboid005.geometry} material={materials.Material_4} position={[0.413, 0.064, -0.716]} rotation={[0, 1.571, 0]} />
          <mesh name="cuboid006" geometry={nodes.cuboid006.geometry} material={materials.Material_4} position={[-0.081, 0.068, -0.706]} rotation={[0, 1.571, 0]} />
        </group>
        <mesh name="circle" geometry={nodes.circle.geometry} material={materials.Material_0} position={[-0.044, 0.075, -0.222]} />
        <mesh name="circle001" geometry={nodes.circle001.geometry} material={materials.Material_1} position={[-0.045, 0.069, -0.222]} />
        <mesh name="cuboid" geometry={nodes.cuboid.geometry} material={materials.Material_2} position={[0, 0, 0.012]} />
        <mesh name="cuboid001" geometry={nodes.cuboid001.geometry} material={materials.Material_2} position={[-0.031, 0.281, 0.231]} rotation={[-Math.PI, 0, 0]} />
        <mesh name="Mainboard" geometry={nodes.Mainboard.geometry} material={materials.Material_3} />
        <mesh name="Mesh_441" geometry={nodes.Mesh_441.geometry} material={materials.Material_6} />
        <mesh name="Mesh_441_1" geometry={nodes.Mesh_441_1.geometry} material={materials.Material_2} />
        <mesh name="Mesh_442" geometry={nodes.Mesh_442.geometry} material={materials.Material_1} />
        <mesh name="Mesh_442_1" geometry={nodes.Mesh_442_1.geometry} material={materials.Material_2} />
        <mesh name="Mesh_443" geometry={nodes.Mesh_443.geometry} material={materials.Material_0} />
        <mesh name="Mesh_443_1" geometry={nodes.Mesh_443_1.geometry} material={materials.Material_1} />
        <mesh name="Mesh_444" geometry={nodes.Mesh_444.geometry} material={materials.Material_1} />
        <mesh name="Mesh_444_1" geometry={nodes.Mesh_444_1.geometry} material={materials.Material_2} />
        <mesh name="Mesh_445" geometry={nodes.Mesh_445.geometry} material={materials.Material_1} />
        <mesh name="Mesh_445_1" geometry={nodes.Mesh_445_1.geometry} material={materials.Material_2} />
      </group>
      <mesh name="cuboid029" geometry={nodes.cuboid029.geometry} material={materials.Material_1} position={[0.693, -0.597, -0.687]} rotation={[0, -0.824, -1.488]} scale={0.896} />
      <mesh name="cuboid083" geometry={nodes.cuboid083.geometry} material={materials.Material_1} position={[0.475, -0.597, -0.485]} rotation={[0, -0.824, -1.488]} scale={0.896} />
      <mesh name="cuboid109" geometry={nodes.cuboid109.geometry} material={materials.Material_1} position={[0.465, -0.575, -0.479]} rotation={[0, -0.824, -1.488]} scale={0.896} />
      <mesh name="cuboid110" geometry={nodes.cuboid110.geometry} material={materials.Material_1} position={[0.461, -0.575, -0.475]} rotation={[0, -0.824, -1.488]} scale={0.896} />
      <mesh name="cuboid161" geometry={nodes.cuboid161.geometry} material={materials.Material_1} position={[0.683, -0.575, -0.68]} rotation={[0, -0.824, -1.488]} scale={0.896} />
      <mesh name="cuboid163" geometry={nodes.cuboid163.geometry} material={materials.Material_1} position={[0.687, -0.575, -0.684]} rotation={[0, -0.824, -1.488]} scale={0.896} />
      <mesh name="cuboid238" geometry={nodes.cuboid238.geometry} material={materials.Material_1} position={[0.693, -0.597, -0.687]} rotation={[0, -0.824, -1.488]} scale={0.896} />
      <mesh name="cuboid292" geometry={nodes.cuboid292.geometry} material={materials.Material_1} position={[0.475, -0.597, -0.485]} rotation={[0, -0.824, -1.488]} scale={0.896} />
      <mesh name="cuboid341" geometry={nodes.cuboid341.geometry} material={materials.Material_1} position={[0.687, -0.575, -0.684]} rotation={[0, -0.824, -1.488]} scale={0.896} />
      <mesh name="cuboid343" geometry={nodes.cuboid343.geometry} material={materials.Material_1} position={[0.683, -0.575, -0.68]} rotation={[0, -0.824, -1.488]} scale={0.896} />
      <mesh name="cuboid394" geometry={nodes.cuboid394.geometry} material={materials.Material_1} position={[0.461, -0.575, -0.475]} rotation={[0, -0.824, -1.488]} scale={0.896} />
      <mesh name="cuboid395" geometry={nodes.cuboid395.geometry} material={materials.Material_1} position={[0.465, -0.575, -0.479]} rotation={[0, -0.824, -1.488]} scale={0.896} />
    </group>
  )
}

useGLTF.preload('/model/mainboard.glb')
