/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/model/power.glb -o src/components/3d-Render/3d/powerSupply.js -k -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Power(props) {
  const { nodes, materials } = useGLTF('/model/power.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_model" position={[-1.079, 0.058, -0.729]} rotation={[-1.725, -0.188, -0.742]} scale={0.2}>
        <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
          <group name="Cylinder001_34" position={[-5.126, -0.631, -0.197]} rotation={[1.619, -0.349, 0.393]} scale={[0.268, 6.774, 0.114]}>
            <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials['Material.008']} />
            <mesh name="Object_55" geometry={nodes.Object_55.geometry} material={materials['Material.009']} />
            <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials['Material.010']} />
          </group>
          <group name="Cylinder002_36" position={[3.345, -0.631, -0.197]} rotation={[1.619, -0.349, 0.393]} scale={[0.286, 6.189, 0.221]}>
            <mesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials['Material.011']} />
            <mesh name="Object_59" geometry={nodes.Object_59.geometry} material={materials['Material.012']} />
            <mesh name="Object_60" geometry={nodes.Object_60.geometry} material={materials['Material.013']} />
          </group>
          <group name="Cylinder_33" position={[-0.002, -0.631, -0.197]} rotation={[1.619, -0.349, 0.393]} scale={[0.286, 6.189, 0.221]}>
            <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials['Material.005']} />
            <mesh name="Object_51" geometry={nodes.Object_51.geometry} material={materials['Material.006']} />
            <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials['Material.007']} />
          </group>
          <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials['Material.001']} position={[-7.802, 4.901, -8.885]} scale={[0.081, 0.239, 0.081]} />
          <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials['Material.001']} position={[-7.906, 4.901, 8.95]} scale={[0.081, 0.239, 0.081]} />
          <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials['Material.001']} position={[7.916, 4.901, 8.95]} scale={[0.081, 0.239, 0.081]} />
          <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.hitam} position={[-7.802, 0, -10.11]} rotation={[-1.567, 0, 0]} scale={[0.081, 0.239, 0.081]} />
          <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials.hitam} position={[-2.861, 0, -10.11]} rotation={[-1.567, 0, 0]} scale={[0.081, 0.239, 0.081]} />
          <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials['Material.001']} position={[7.926, 4.901, -8.865]} scale={[0.081, 0.239, 0.081]} />
          <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials['Material.004']} position={[-8.15, -1.997, 9.208]} scale={[1.031, 0.623, 1]} />
          <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.abuabu} position={[0, 5.017, 0]} scale={[1.947, 0.047, 1.947]} />
          <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.putih} position={[0.035, 3.148, -0.004]} rotation={[0, 0.175, Math.PI]} scale={5.244} />
          <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.abuabu} position={[-7.904, 4.659, 8.965]} rotation={[0, 0, 3.141]} scale={0.472} />
          <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.hitam} position={[-5.336, -0.002, -8.689]} scale={[1.919, 1.569, 1.68]} />
          <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials.material} position={[-6.329, 0.358, -8.713]} scale={[0.082, 0.239, 1.432]} />
          <mesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials.material} position={[-5.383, -0.519, -8.713]} scale={[0.082, 0.239, 1.432]} />
          <mesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials.hitam} position={[-9.888, 0, 0]} scale={[0.178, 2.45, 9.874]} />
          <mesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials.hitam} position={[9.87, 0, 0]} scale={[0.178, 2.45, 9.823]} />
          <mesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials['Material.002']} position={[-0.255, 0, 9.249]} scale={[9.449, 4.233, 0.075]} />
          <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials.material} position={[-4.31, 0.358, -8.713]} scale={[0.082, 0.239, 1.432]} />
          <mesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials['Material.002']} position={[10.312, -1.88, 8.977]} rotation={[1.571, 0.007, -1.586]} scale={5.224} />
          <mesh name="Object_76" geometry={nodes.Object_76.geometry} material={materials['Material.003']} position={[-10.111, -0.818, -8.759]} rotation={[1.571, -0.007, 1.572]} scale={1.846} />
          <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials['Material.004']} position={[-5.293, -3.218, -10.257]} rotation={[-0.005, 0.156, -3.141]} scale={[1.524, 1.161, 0.425]} />
          <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.hitam} position={[-5.293, -3.325, -8.263]} rotation={[0, 0, -Math.PI]} scale={[1.78, 1.448, 2.194]} />
          <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.abuabu} position={[7.915, 4.634, -8.871]} rotation={[0, 0, 3.141]} scale={0.507} />
          <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.abuabu} position={[7.915, 4.634, 8.961]} rotation={[0, 0, 3.141]} scale={0.507} />
          <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.abuabu} position={[-7.796, 4.634, -8.871]} rotation={[0, 0, 3.141]} scale={0.507} />
          <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.abuabu} scale={[9.946, 5.219, 9.946]} />
          <mesh name="Object_64" geometry={nodes.Object_64.geometry} material={materials.material} position={[-4.772, -2.49, -10.791]} rotation={[0.015, -1.338, -1.556]} scale={0.813} />
          <mesh name="Object_66" geometry={nodes.Object_66.geometry} material={materials['put.001']} position={[-6.634, -2.776, -10.499]} rotation={[0.015, -1.338, -1.556]} scale={0.864} />
          <mesh name="Object_68" geometry={nodes.Object_68.geometry} material={materials['put.002']} position={[-7.938, 3.041, 9.965]} rotation={[1.6, -0.001, -0.003]} scale={0.711} />
          <mesh name="Object_70" geometry={nodes.Object_70.geometry} material={materials['put.003']} position={[2.15, 3.041, 9.965]} rotation={[1.6, -0.001, -0.003]} scale={0.711} />
          <mesh name="Object_72" geometry={nodes.Object_72.geometry} material={materials['put.004']} position={[2.15, -0.742, 9.965]} rotation={[1.6, -0.001, -0.003]} scale={0.711} />
          <mesh name="Object_74" geometry={nodes.Object_74.geometry} material={materials['put.005']} position={[-8.068, -0.8, 9.966]} rotation={[1.6, -0.001, -0.003]} scale={0.711} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/model/power.glb')
