/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/model/ram.glb -o src/components/3d-Render/3d/ram.js -k -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Ram(props) {
  const { nodes, materials } = useGLTF('/model/ram.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Mesh_0" geometry={nodes.Mesh_0.geometry} material={materials.Material_0} />
      <mesh name="Mesh_0_1" geometry={nodes.Mesh_0_1.geometry} material={materials.Material_1} />
      <mesh name="Mesh_1" geometry={nodes.Mesh_1.geometry} material={materials.Material_0} />
      <mesh name="Mesh_1_1" geometry={nodes.Mesh_1_1.geometry} material={materials.Material_1} />
    </group>
  )
}

useGLTF.preload('/model/ram.glb')
