/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/model/ram.glb -o src/components/3d-Render/3d/ram.js -k -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function RamModel(props) {
  const { nodes, materials } = useGLTF('/model/ram.glb')
  return (
    <group {...props} dispose={null}>
      <group name="ram" position={[-0.123, -0.724, 0]} rotation={[-1.972, -0.414, 2.405]}>
        <group name="RAMtriangulatedobjcleanermaterialmergergles" scale={1.192}>
          <mesh name="Object_10001" geometry={nodes.Object_10001.geometry} material={materials['Material.022']} />
          <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials['Material.023']} />
          <mesh name="Object_2" geometry={nodes.Object_2.geometry} material={materials['Material.014']} />
          <mesh name="Object_3" geometry={nodes.Object_3.geometry} material={materials['Material.015']} />
          <mesh name="Object_4001" geometry={nodes.Object_4001.geometry} material={materials['Material.016']} />
          <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials['Material.017']} />
          <mesh name="Object_6001" geometry={nodes.Object_6001.geometry} material={materials['Material.018']} />
          <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials['Material.019']} />
          <mesh name="Object_8001" geometry={nodes.Object_8001.geometry} material={materials['Material.020']} />
          <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials['Material.021']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/model/ram.glb')
