/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/model/ram1.glb -o src/components/3d-Render/3d/ram.js -k -r public 
Author: Astrien (https://sketchfab.com/Astrien)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/kingston-hyperx-fury-black-ram-module-3d9499b5337f475d8bbb1eccdb20e73d
Title: Kingston HyperX Fury Black RAM Module
*/

import { useGLTF } from '@react-three/drei'

export function RamModel(props) {
  const { nodes, materials } = useGLTF('/model/ram1.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_model" position={[-0.048, 0, 0]} rotation={[-Math.PI / 2, 0, 3.141]}>
        <mesh name="Object_2" geometry={nodes.Object_2.geometry} material={materials['Material.001']} />
        <mesh name="Object_3" geometry={nodes.Object_3.geometry} material={materials['Material.002']} />
        <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials['Material.003']} />
        <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials['Material.004']} />
        <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials['Material.006']} />
        <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials['Material.008']} />
        <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials['Material.010']} />
        <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials['Material.012']} />
        <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials['Material.013']} />
        <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials['Material.009']} />
      </group>
    </group>
  )
}

useGLTF.preload('/model/ram1.glb')
