/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/model/ssd.glb -o src/components/3d-Render/3d/Ssd.js -k -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Ssd(props) {
  const { nodes, materials } = useGLTF('/model/ssd.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_model" position={[0, -0.607, 0]} rotation={[-0.743, 0.719, -2.598]}>
        <mesh name="Object_2001" geometry={nodes.Object_2001.geometry} material={materials['Material.024']} />
        <mesh name="Object_3001" geometry={nodes.Object_3001.geometry} material={materials.None} />
      </group>
    </group>
  )
}

useGLTF.preload('/model/ssd.glb')
