/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/model/ssd.glb -o src/components/3d-Render/3d/ssd.js -k -r public 
Author: cityon360 (https://sketchfab.com/cityon360)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ssd-samsung-980-pro-1tb-208b846d5a5948368b4ad0676bf4ab97
Title: SSD Samsung 980 PRO 1TB
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Ssd(props) {
  const { nodes, materials } = useGLTF('/model/ssd.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
        <mesh name="Object_2" geometry={nodes.Object_2.geometry} material={materials.Material} />
        <mesh name="Object_3" geometry={nodes.Object_3.geometry} material={materials.None} />
      </group>
    </group>
  )
}

useGLTF.preload('/model/ssd.glb')
